---
title: "efg's R Notes:  EBImage:  Color"
output: html_document
---

**[RNotes](../../index.html) | [EBImage](index.html)** 

*****

```{r}
library(EBImage)
```

# Color and Image Color Mode Conversions

```{r, fig.width=8, fig.height=2}
par(mfrow=c(1,2))
x <- readImage(system.file("images", "shapes.png", package="EBImage"))
display(x)
y <- channel(x, 'asgreen')
display(y)
```

## rgbImage

```{r, fig.width=8, fig.height=3.5}
par(mfrow=c(1,2))
x <- readImage(system.file('images', 'nuclei.tif', package='EBImage'))
y <- readImage(system.file('images', 'cells.tif', package='EBImage'))
display(x, title='Cell nuclei', all=TRUE)
display(y, title='Cell bodies', all=TRUE)
```

```{r, fig.width=8, fig.height=3.5}
cells <- rgbImage(green=1.5*y, blue=x)
display(cells, title='Cells', all=TRUE)
```

## colorMode example

```{r, fig.width=8, fig.height=3.5}
x <- readImage(system.file('images', 'nuclei.tif', package='EBImage'))
x <- x[,,1:3]
display(x, title='Cell nuclei', all=TRUE)
colorMode(x) = Color
display(x, title='Cell nuclei in RGB', all=TRUE)
```

# Color Code Labels

```{r, fig.width=6, fig.height=2}
x <- readImage(system.file('images', 'shapes.png', package='EBImage'))
x <- x[110:512,1:130]
y <- bwlabel(x)
z <- colorLabels(y)
display(z, title='Colored segmentation')
```

*****

```{r}
packageVersion("EBImage")
```

*efg*  
`r format(Sys.time(), "%Y-%m-%d  %H%M")`  