---
title: 'EBImage: Local Curvature'
author: "Earl F Glynn"
output: html_document
---

```{r}
library(EBImage)
```

Computes signed curvature along a line. 

## Curvature goes as the inverse of the radius of a circle

```{r, fig.width=6}
range <- seq(3.5,33.5,by=2)
plotRange <- seq(0.5,33.5,length=100)
circleRes <- array(dim=length(range))
names(circleRes) <- range
for (i in  seq_along(1:length(range))) 
{
  y <- as.Image(makeBrush('disc', size=2*range[i]))
  y <- ocontour(y)[[1]]
  circleRes[i] <- abs(mean(localCurvature(x=y,h=range[i])$curvature, na.rm=TRUE))
}
plot(range, circleRes, ylim=c(0,max(circleRes, na.rm=TRUE)), 
     xlab='Circle Radius', ylab='Curvature', 
     type='p', xlim=range(plotRange))
points(plotRange, 1/plotRange, type='l')
grid()
```

## Calculate curvature
  
```{r, fig.width=6, fig.height=2.5}
f <- system.file("images", "sample.png", package="EBImage")
x <- readImage(f)
mk <- makeBrush(size=21, shape="Gaussian", sigma=9)
x2 <- filter2(x, filter=mk)
x2 <- thresh(x2, w=50, h=50)
x2 <-bwlabel(x2)
contours <- ocontour(x2)
curv <- localCurvature(x=contours[[2]], h=11)$curvature
I <- Image(0, dim=dim(x))
imageData(I)[contours[[2]]+1]=abs(curv)
x2[x2!=2] <- 0
display(combine(x2, 10*I), title = "Image curvature", all=TRUE)
```

Are the images above the expected ones?

*efg*  
`r format(Sys.time(), "%Y-%m-%d  %H%M")` 